#ifndef BINDINGS_H
#define BINDINGS_H

/* Automatically generated by cbindgen. Do not edit manually. */

#include "stdint.h"
#include "sys/types.h"

int32_t add_numbers(int32_t a, int32_t b);

char *gohttp(void);

#endif  /* BINDINGS_H */
