name: Go service workflow

on:
  pull_request:
    branches:
      - main

concurrency:
  group: multilanguage_sdk_service_${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout
  id-token: write # for authenticating to Google Cloud Platform
  pull-requests: write # for updating pr

jobs:
  build-multilanguage-sdk:
    uses: ./.github/workflows/engine-ci.yml
    secrets: inherit
