name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: multilanguage_sdk_service_${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout
  id-token: write # for authenticating to Google Cloud Platform
  pull-requests: write # for updating pr

jobs:
  build-multilanguage-sdk:
    uses: ./.github/workflows/engine-ci.yml
    secrets: inherit

  # release-multilanguage-sdk:
  #   runs-on: ubuntu-latest
  #   needs: build-multilanguage-sdk
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Get Next Version
  #       id: semver
  #       uses: ietf-tools/semver-action@v1
  #       with:
  #         token: ${{ github.token }}
  #         branch: main
  #         noVersionBumpBehavior: silent
  #         skipInvalidTags: true

  #     - name: Create Release
  #       uses: ncipollo/release-action@v1
  #       if: steps.semver.outputs.next
  #       with:
  #         allowUpdates: true
  #         # draft: true
  #         generateReleaseNotes: true
  #         makeLatest: true
  #         tag: ${{ steps.semver.outputs.next }}
  #         token: ${{ secrets.CONTAINIFYCI_RELEASE_TOKEN }}
